#!/bin/bash
#set argument
. model/checkParam
filePath="$5"
function backup(){
	ssh  192.168.1.213 > /dev/null 2>&1  << eeooff
	cd /tmp
	mv 123 123.bak $(date +"%Y-%m-%d@%H:%M:%S~")
eeooff
}

function copy(){
	checkParam
	src=$(echo $filePath|awk -F ' ' '{print $1}'|awk -F '=' '{print $2}') > $NULL
	dest=$(echo $filePath|awk -F ' ' '{print $2}'|awk -F '=' '{print $2}') > $NULL
	state=$(echo $filePath|awk -F ' ' '{print $3}'|awk -F '=' '{print $2}') > $NULL
	srcFileName=$(basename $src)
	for i in $host
	do
		scp -r $src root@$i:$dest 2>&1 > $NULL
	done
}
copy
