#!/bin/bash
. model/checkParam
CMD="$5 $6 $7 $8 $9"
function shell(){
	checkParam
	for i in $host	
	do
		echo -e $YELLOW "\b$i | CHANGED | rc=0 >>"
		ssh $i $CMD 
		echo -e "$RESETTEMINAL"
	done
}
shell
